apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: ${NAMESPACE}


spec:
  provider:
    vault:
      server: ${VAULT_ADDR}
      path: ${VAULT_PATH}
      namespace: admin
      path: kv-${ENV}
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: ${NAMESPACE}
data:
  token: ${VAULT_TOKEN_B64}
