apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: ${NAMESPACE}
spec:
  provider:
    vault:
      server: ${VAULT_ADDR}
      path: ${VAULT_PATH}
      # Version is the Vault KV secret engine version.
      # This can be either v1 or v2, defaults to v2
      version: v2
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: vault-token
          key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: ${NAMESPACE}
data:
  token: ${VAULT_TOKEN_B64}
