apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-admin
  namespace: ${NAMESPACE}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ci-admin-crb-${NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: ci-admin
    namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin

---
apiVersion: v1
kind: Secret
metadata:
  name: ci-admin-token
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/service-account.name: ci-admin
type: kubernetes.io/service-account-token
