apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-bot
  namespace: ${NAMESPACE}


---
# Example: namespace-scoped permissions (edit as needed)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-bot-role
  namespace: ${NAMESPACE}
rules:
  # Core ("" apiGroup)
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - configmaps
      - secrets
      - events
      - replicationcontrollers
      - serviceaccounts
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Apps workloads
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Batch workloads
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Autoscaling
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ci-bot-rb
  namespace: ${NAMESPACE}
subjects:
  - kind: ServiceAccount
    name: ci-bot
    namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ci-bot-role

---
# This is the “long-lived” token secret (manual creation is required on modern k8s)
apiVersion: v1
kind: Secret
metadata:
  name: ci-bot-token
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/service-account.name: ci-bot
type: kubernetes.io/service-account-token
