apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-prd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/org/config-repo.git
    targetRevision: main
    path: argocd/prd # Watches a specific env folder
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
